### ISSUE TITLE
Set signal_bandwidth error

### ISSUE THREAD

**Issue by aidan-fransen** [belyalov/stm32-hal-libraries#8]
Thanks for making this library available, saved me a lot of time.

However, when using this library I did notice there was a mistake in the lora_set_signal_bandwidth function.

The new bandwidth value is OR'd with the old value instead of replacing it. You can see the line I replaced it with below, it seems to work well.

![image](https://user-images.githubusercontent.com/94873777/161448920-2f8e40a9-518c-4233-9aab-317845d6c15b.png)

**Comment by belyalov** [comment]
Hi @aidan-fransen 

Thanks for noting!

Please feel free to make PR to fix it, I'd really appreciated!
